/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author oreoc
 */
public class DashboardMahasiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardMahasiswa.class.getName());
    private int mahaId;
    private String nama;
    /**
     * Creates new form DashboardMahasiswa
     */
    public DashboardMahasiswa(int mahaId, String nama) {
        initComponents();
        this.mahaId = mahaId;
        this.nama = nama;
        jLabelUcapanSelamatDatang.setText("Selamat datang, " + nama);
        loadQuiz();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDaftarQuizMahasiswa = new javax.swing.JTable();
        jButtonMulaiQuiz = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelUcapanSelamatDatang = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Daftar Quiz");
        jLabel1.setToolTipText("");

        TabelDaftarQuizMahasiswa.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        TabelDaftarQuizMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelDaftarQuizMahasiswa);

        jButtonMulaiQuiz.setBackground(new java.awt.Color(153, 255, 153));
        jButtonMulaiQuiz.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonMulaiQuiz.setForeground(new java.awt.Color(102, 102, 102));
        jButtonMulaiQuiz.setText("Mulai Quiz");
        jButtonMulaiQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMulaiQuizActionPerformed(evt);
            }
        });

        jButtonRefresh.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRefresh.setText("Segarkan");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jLabelUcapanSelamatDatang.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabelUcapanSelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUcapanSelamatDatang.setText("Selamat datang");

        jButtonLogout.setBackground(new java.awt.Color(255, 102, 102));
        jButtonLogout.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setText("EduSpeedQuizz");
        jLabelLogo.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUcapanSelamatDatang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelUcapanSelamatDatang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLogout)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonMulaiQuiz)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRefresh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMulaiQuiz)
                    .addComponent(jButtonRefresh))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMulaiQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMulaiQuizActionPerformed
    int row = TabelDaftarQuizMahasiswa.getSelectedRow();
            if (row >= 0) {
                int quizId = Integer.parseInt(TabelDaftarQuizMahasiswa.getValueAt(row, 0).toString());
                int waktu = Integer.parseInt(TabelDaftarQuizMahasiswa.getValueAt(row, 2).toString());
                HalamanQuiz quizPage = new HalamanQuiz(mahaId, quizId, waktu);
                quizPage.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih quiz dulu!");
            }
    }//GEN-LAST:event_jButtonMulaiQuizActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
    loadQuiz();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Yakin ingin logout?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose();  // Tutup dashboard mahasiswa
        new Login().setVisible(true);  // Buka kembali form login
    }
    }//GEN-LAST:event_jButtonLogoutActionPerformed
    private void loadQuiz() {
            try (Connection con = Koneksi.getConnection()) {
                String query = "SELECT tbl_quiz.id, nama_quiz, waktu_menit, nama_lengkap AS dosen FROM tbl_quiz JOIN tbl_user ON tbl_quiz.dosen_id = tbl_user.id";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(query);

                DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama Quiz", "Waktu (menit)", "Dosen"}, 0);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getInt("id"), rs.getString("nama_quiz"), rs.getInt("waktu_menit"), rs.getString("dosen")});
                }
                TabelDaftarQuizMahasiswa.setModel(model);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error loading quiz: " + ex.getMessage());
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new DashboardMahasiswa(1, "Test Mahasiswa").setVisible(true);  // Dummy param
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelDaftarQuizMahasiswa;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMulaiQuiz;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelUcapanSelamatDatang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
