/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author oreoc
 */
public class DashboardDosen extends javax.swing.JFrame {
    private int quizId;
    private int dosenId;
    private String nama;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardDosen.class.getName());

    /**
     * Creates new form DashboardDosen
     */
    public DashboardDosen(int dosenId, String nama) {
        initComponents();
        this.dosenId = dosenId;
        this.nama = nama;
        jLabelUcapanSelamatDatang.setText("Selamat datang, " + nama);
        loadQuiz(); // Load data quiz saat init
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDaftarQuizDosen = new javax.swing.JTable();
        jButtonLihatSkorMahasiswa = new javax.swing.JButton();
        jButtonBuatQuiz = new javax.swing.JButton();
        jButtonEditQuiz = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonLogout = new javax.swing.JButton();
        jLabelUcapanSelamatDatang = new javax.swing.JLabel();
        jLabel3Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Daftar Quiz");
        jLabel1.setToolTipText("");

        TabelDaftarQuizDosen.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        TabelDaftarQuizDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelDaftarQuizDosen);

        jButtonLihatSkorMahasiswa.setBackground(new java.awt.Color(153, 255, 153));
        jButtonLihatSkorMahasiswa.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonLihatSkorMahasiswa.setForeground(new java.awt.Color(102, 102, 102));
        jButtonLihatSkorMahasiswa.setText("Lihat Skor Mahasiswa");
        jButtonLihatSkorMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLihatSkorMahasiswaActionPerformed(evt);
            }
        });

        jButtonBuatQuiz.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonBuatQuiz.setForeground(new java.awt.Color(102, 102, 102));
        jButtonBuatQuiz.setText("Buat Quiz Baru");
        jButtonBuatQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuatQuizActionPerformed(evt);
            }
        });

        jButtonEditQuiz.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonEditQuiz.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEditQuiz.setText("Edit Quiz");
        jButtonEditQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditQuizActionPerformed(evt);
            }
        });

        jButtonRefresh.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRefresh.setText("Segarkan");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(255, 102, 102));
        jButtonHapus.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonHapus.setForeground(new java.awt.Color(102, 102, 102));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jButtonLogout.setBackground(new java.awt.Color(255, 102, 102));
        jButtonLogout.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Keluar");
        jButtonLogout.setBorder(null);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelUcapanSelamatDatang.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUcapanSelamatDatang.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabelUcapanSelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUcapanSelamatDatang.setText("Selamat datang");

        jLabel3Logo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3Logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3Logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3Logo.setText("EduSpeedQuizz");
        jLabel3Logo.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUcapanSelamatDatang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3Logo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelUcapanSelamatDatang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLogout)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(287, 287, 287))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLihatSkorMahasiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuatQuiz)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditQuiz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRefresh))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLihatSkorMahasiswa)
                    .addComponent(jButtonBuatQuiz)
                    .addComponent(jButtonEditQuiz)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonHapus))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLihatSkorMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatSkorMahasiswaActionPerformed
int row = TabelDaftarQuizDosen.getSelectedRow();
        if (row >= 0) {
            int quizId = Integer.parseInt(TabelDaftarQuizDosen.getValueAt(row, 0).toString());
            String namaQuiz = TabelDaftarQuizDosen.getValueAt(row, 1).toString();
            RiwayatNilai riwayat = new RiwayatNilai(quizId, namaQuiz, this);
            riwayat.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih quiz dulu!");
        }
    }//GEN-LAST:event_jButtonLihatSkorMahasiswaActionPerformed

    private void jButtonBuatQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuatQuizActionPerformed
    FormNewQuiz newQuiz = new FormNewQuiz(dosenId);
        newQuiz.setVisible(true);
    }//GEN-LAST:event_jButtonBuatQuizActionPerformed

    private void jButtonEditQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditQuizActionPerformed
int row = TabelDaftarQuizDosen.getSelectedRow();
    if (row >= 0) {
        int quizId = Integer.parseInt(TabelDaftarQuizDosen.getValueAt(row, 0).toString());
        
        // Langsung buka FormTambahAndEditSoal dengan quizId yang dipilih
        FormTambahAndEditSoal editSoalForm = new FormTambahAndEditSoal(quizId);
        editSoalForm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadQuiz();  // Refresh tabel setelah form ditutup (jika ada perubahan nama quiz dari tempat lain)
            }
        });
        editSoalForm.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Pilih quiz terlebih dahulu untuk diedit!");
    }
    }//GEN-LAST:event_jButtonEditQuizActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
    loadQuiz();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
    int row = TabelDaftarQuizDosen.getSelectedRow();
    if (row >= 0) {
        int quizId = Integer.parseInt(TabelDaftarQuizDosen.getValueAt(row, 0).toString());
        String namaQuiz = TabelDaftarQuizDosen.getValueAt(row, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus quiz \"" + namaQuiz + "\"?\n" +
            "Semua soal dan hasil nilai terkait juga akan terhapus!", 
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection con = Koneksi.getConnection()) {
                // Hapus hasil nilai dulu (foreign key)
                PreparedStatement pstHasil = con.prepareStatement("DELETE FROM tbl_hasil WHERE quiz_id = ?");
                pstHasil.setInt(1, quizId);
                pstHasil.executeUpdate();

                // Hapus soal
                PreparedStatement pstSoal = con.prepareStatement("DELETE FROM tbl_soal WHERE quiz_id = ?");
                pstSoal.setInt(1, quizId);
                pstSoal.executeUpdate();

                // Hapus quiz
                PreparedStatement pstQuiz = con.prepareStatement("DELETE FROM tbl_quiz WHERE id = ? AND dosen_id = ?");
                pstQuiz.setInt(1, quizId);
                pstQuiz.setInt(2, dosenId);
                int deleted = pstQuiz.executeUpdate();

                if (deleted > 0) {
                    JOptionPane.showMessageDialog(this, "Quiz berhasil dihapus!");
                    loadQuiz();  // Refresh tabel
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus quiz (mungkin bukan milik Anda)");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error hapus quiz: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih quiz yang ingin dihapus!");
    }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Yakin ingin logout?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose();  // Tutup dashboard dosen
        new Login().setVisible(true);  // Buka kembali form login
    }
    }//GEN-LAST:event_jButtonLogoutActionPerformed
    private void loadQuiz() {
        try (Connection con = Koneksi.getConnection()) {
            String query = "SELECT id, nama_quiz, waktu_menit FROM tbl_quiz WHERE dosen_id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, dosenId);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama Quiz", "Waktu (menit)"}, 0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("id"), rs.getString("nama_quiz"), rs.getInt("waktu_menit")});
            }
            TabelDaftarQuizDosen.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading quiz: " + ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        // Pakai dummy untuk test; asli panggil dengan param dari Login
        new DashboardDosen(1, "Test Dosen").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelDaftarQuizDosen;
    private javax.swing.JButton jButtonBuatQuiz;
    private javax.swing.JButton jButtonEditQuiz;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonLihatSkorMahasiswa;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3Logo;
    private javax.swing.JLabel jLabelUcapanSelamatDatang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
