/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz;

import com.formdev.flatlaf.FlatClientProperties;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author oreoc
 */
public class FormTambahAndEditSoal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahAndEditSoal.class.getName());
    private int quizId;
    private boolean isEdit = false;
    private int selectedSoalId = -1;
    
    /**
     * Creates new form FormTambahAndEditSoal
     */
    public FormTambahAndEditSoal(int quizId) {
        initComponents();
        this.quizId = quizId;
        loadNamaQuiz();
        loadSoalToTable();  // Load list soal existing
        
        jTextAreaPertanyaan.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT,"Masukkan Pertanyaan");
        txtOpsiA.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Untuk Opsi A");
        txtOpsiB.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Untuk Opsi B");
        txtOpsiC.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Untuk Opsi C");
        txtOpsiD.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukkan Untuk Opsi D");
        
    }
    private void loadSoalToTable() {
    try (Connection con = Koneksi.getConnection()) {
        PreparedStatement pst = con.prepareStatement("SELECT id, pertanyaan FROM tbl_soal WHERE quiz_id = ?");
        pst.setInt(1, quizId);
        ResultSet rs = pst.executeQuery();
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Pertanyaan"}, 0);
        while (rs.next()) {
            model.addRow(new Object[]{rs.getInt("id"), rs.getString("pertanyaan")});
        }
        jTableSoal.setModel(model);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error load soal: " + ex.getMessage());
    }
    }

    private void loadNamaQuiz() {
    try (Connection con = Koneksi.getConnection()) {
        String query = "SELECT nama_quiz FROM tbl_quiz WHERE id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, quizId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String namaQuiz = rs.getString("nama_quiz");
            jLabelTambahSoalKeVariabelNamaSoal.setText("Edit Soal Quiz: " + namaQuiz);
        } else {
            jLabelTambahSoalKeVariabelNamaSoal.setText("Edit Soal Quiz: (Quiz tidak ditemukan)");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error load nama quiz: " + ex.getMessage());
        jLabelTambahSoalKeVariabelNamaSoal.setText("Edit Soal Quiz: Error");
        ex.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPertanyaan = new javax.swing.JTextArea();
        jButtonBatal = new javax.swing.JButton();
        jButtonSelesai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOpsiA = new javax.swing.JTextField();
        txtOpsiB = new javax.swing.JTextField();
        txtOpsiC = new javax.swing.JTextField();
        txtOpsiD = new javax.swing.JTextField();
        cbJawaban = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTambahSoalKeVariabelNamaSoal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSoal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Pertanyaan");

        jButtonSimpan.setBackground(new java.awt.Color(153, 255, 153));
        jButtonSimpan.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonSimpan.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSimpan.setText("Simpan Soal");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jTextAreaPertanyaan.setColumns(20);
        jTextAreaPertanyaan.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        jTextAreaPertanyaan.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPertanyaan);

        jButtonBatal.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonBatal.setForeground(new java.awt.Color(102, 102, 102));
        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonSelesai.setBackground(new java.awt.Color(102, 204, 255));
        jButtonSelesai.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonSelesai.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSelesai.setText("Selesai");
        jButtonSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelesaiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("A.");

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("B.");

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("C.");

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("D.");

        txtOpsiA.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        txtOpsiA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpsiAActionPerformed(evt);
            }
        });

        txtOpsiB.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        txtOpsiB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpsiBActionPerformed(evt);
            }
        });

        txtOpsiC.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        txtOpsiC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpsiCActionPerformed(evt);
            }
        });

        txtOpsiD.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N

        cbJawaban.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        cbJawaban.setForeground(new java.awt.Color(102, 102, 102));
        cbJawaban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pilih Jawaban Yang Benar");

        jButtonRefresh.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRefresh.setText("Segarkan");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(255, 102, 102));
        jButtonHapus.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonHapus.setForeground(new java.awt.Color(102, 102, 102));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonEdit.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(102, 102, 102));
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabelTambahSoalKeVariabelNamaSoal.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabelTambahSoalKeVariabelNamaSoal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTambahSoalKeVariabelNamaSoal.setText("Tambah Soal ke: Variabel");

        jTableSoal.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jTableSoal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSoal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTambahSoalKeVariabelNamaSoal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTambahSoalKeVariabelNamaSoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtOpsiD, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonHapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonBatal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonEdit)
                                    .addGap(11, 11, 11)
                                    .addComponent(jButtonSimpan))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtOpsiC, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)
                                .addComponent(txtOpsiB, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOpsiA, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRefresh)))
                                .addGap(3, 3, 3))
                            .addComponent(jButtonSelesai, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(48, 48, 48)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOpsiA, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOpsiB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRefresh))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOpsiC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpsiD, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelesai)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonEdit))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
String pertanyaan = jTextAreaPertanyaan.getText().trim();
    String opsiA = txtOpsiA.getText().trim();
    String opsiB = txtOpsiB.getText().trim();
    String opsiC = txtOpsiC.getText().trim();
    String opsiD = txtOpsiD.getText().trim();
    String jawaban = (String) cbJawaban.getSelectedItem();

    if (pertanyaan.isEmpty() || opsiA.isEmpty() || opsiB.isEmpty() || opsiC.isEmpty() || opsiD.isEmpty() || jawaban == null) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    try (Connection con = Koneksi.getConnection()) {
        PreparedStatement pst;
        if (isEdit) {
            // Mode Update
            pst = con.prepareStatement("UPDATE tbl_soal SET pertanyaan=?, opsi_a=?, opsi_b=?, opsi_c=?, opsi_d=?, jawaban_benar=? WHERE id=?");
            pst.setString(1, pertanyaan);
            pst.setString(2, opsiA);
            pst.setString(3, opsiB);
            pst.setString(4, opsiC);
            pst.setString(5, opsiD);
            pst.setString(6, jawaban);
            pst.setInt(7, selectedSoalId);
            JOptionPane.showMessageDialog(this, "Soal berhasil diupdate!");
        } else {
            // Mode Insert
            pst = con.prepareStatement("INSERT INTO tbl_soal (quiz_id, pertanyaan, opsi_a, opsi_b, opsi_c, opsi_d, jawaban_benar) VALUES (?, ?, ?, ?, ?, ?, ?)");
            pst.setInt(1, quizId);
            pst.setString(2, pertanyaan);
            pst.setString(3, opsiA);
            pst.setString(4, opsiB);
            pst.setString(5, opsiC);
            pst.setString(6, opsiD);
            pst.setString(7, jawaban);
            JOptionPane.showMessageDialog(this, "Soal berhasil ditambahkan!");
        }
        pst.executeUpdate();
        clearFields();  // Reset form
        loadSoalToTable();  // Refresh tabel
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error simpan soal: " + ex.getMessage());
    }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
    resetForm();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelesaiActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButtonSelesaiActionPerformed

    private void txtOpsiAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpsiAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpsiAActionPerformed

    private void txtOpsiBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpsiBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpsiBActionPerformed

    private void txtOpsiCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpsiCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpsiCActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
    loadSoalToTable();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
int row = jTableSoal.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih soal dulu!");
        return;
    }
    int id = (int) jTableSoal.getValueAt(row, 0);
    int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus soal ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try (Connection con = Koneksi.getConnection()) {
            PreparedStatement pst = con.prepareStatement("DELETE FROM tbl_soal WHERE id = ?");
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Soal dihapus!");
            loadSoalToTable();  // Refresh
            clearFields();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error hapus: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
    int row = jTableSoal.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih soal dari tabel dulu!");
        return;
    }
    selectedSoalId = (int) jTableSoal.getValueAt(row, 0);  // Ambil ID dari kolom 0
    loadDataForEdit();  // Load data ke form
    isEdit = true;
    jButtonSimpan.setText("Update");
    }//GEN-LAST:event_jButtonEditActionPerformed
    private void resetForm() {
        jTextAreaPertanyaan.setText("");
        txtOpsiA.setText("");
        txtOpsiB.setText("");
        txtOpsiC.setText("");
        txtOpsiD.setText("");
        cbJawaban.setSelectedIndex(0);
        isEdit = false;
        selectedSoalId = -1;
        jButtonSimpan.setText("Simpan Soal");
    }
    
    private void loadDataForEdit() {
    try (Connection con = Koneksi.getConnection()) {
        PreparedStatement pst = con.prepareStatement("SELECT * FROM tbl_soal WHERE id = ?");
        pst.setInt(1, selectedSoalId);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            jTextAreaPertanyaan.setText(rs.getString("pertanyaan"));
            txtOpsiA.setText(rs.getString("opsi_a"));
            txtOpsiB.setText(rs.getString("opsi_b"));
            txtOpsiC.setText(rs.getString("opsi_c"));
            txtOpsiD.setText(rs.getString("opsi_d"));
            cbJawaban.setSelectedItem(rs.getString("jawaban_benar"));
        } else {
            JOptionPane.showMessageDialog(this, "Data soal tidak ditemukan!");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error load data edit: " + ex.getMessage());
    }
    }
    private void clearFields() {
    jTextAreaPertanyaan.setText("");
    txtOpsiA.setText("");
    txtOpsiB.setText("");
    txtOpsiC.setText("");
    txtOpsiD.setText("");
    cbJawaban.setSelectedIndex(0);
    isEdit = false;
    selectedSoalId = -1;
    jButtonSimpan.setText("Simpan");  // Kembali ke mode tambah
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new FormTambahAndEditSoal(1).setVisible(true);  // Dummy quizId=1
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJawaban;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSelesai;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTambahSoalKeVariabelNamaSoal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSoal;
    private javax.swing.JTextArea jTextAreaPertanyaan;
    private javax.swing.JTextField txtOpsiA;
    private javax.swing.JTextField txtOpsiB;
    private javax.swing.JTextField txtOpsiC;
    private javax.swing.JTextField txtOpsiD;
    // End of variables declaration//GEN-END:variables
}
