/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author oreoc
 */
public class HalamanQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HalamanQuiz.class.getName());
    private int mahaId, quizId, waktuMenit;
    private List<Question> soalList = new ArrayList<>();
    private int currentSoal = 0;
    private int skor = 0;
    private Timer timer;
    private int sisaDetik;
    private ButtonGroup group = new ButtonGroup();
    /**
     * Creates new form HalamanQuiz
     */
    public HalamanQuiz(int mahaId, int quizId, int waktuMenit) {
        initComponents();
        this.mahaId = mahaId;
        this.quizId = quizId;
        this.waktuMenit = waktuMenit;
        this.sisaDetik = waktuMenit * 60;
        jLabelUntukQuizNamaQuiz.setText("Quiz: " + getNamaQuiz());  // Ambil nama quiz dari DB
        group.add(jRadioButtonA);
        group.add(jRadioButtonB);
        group.add(jRadioButtonC);
        group.add(jRadioButtonD);
        loadSoal();
        tampilSoal();
        startTimer();
        addJawabListener();
    }
    private int jumlahBenar = 0;  // Counter jawaban benar
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jProgressBarQuiz = new javax.swing.JProgressBar();
        jLabelPenandaSoalKeBerapaDariKeBerapa = new javax.swing.JLabel();
        jLabelRuangSoal = new javax.swing.JLabel();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jRadioButtonD = new javax.swing.JRadioButton();
        jLabelSkorRealtime = new javax.swing.JLabel();
        jButtonSelesaiPaksadanKumpul = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelUntukQuizNamaQuiz = new javax.swing.JLabel();
        jLabelWaktuTersisa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPenandaSoalKeBerapaDariKeBerapa.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabelPenandaSoalKeBerapaDariKeBerapa.setForeground(new java.awt.Color(102, 102, 102));
        jLabelPenandaSoalKeBerapaDariKeBerapa.setText("Soal ... dari ....");

        jLabelRuangSoal.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabelRuangSoal.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRuangSoal.setText("Soal");

        buttonGroup1.add(jRadioButtonA);
        jRadioButtonA.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jRadioButtonA.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonB);
        jRadioButtonB.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jRadioButtonB.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonC);
        jRadioButtonC.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jRadioButtonC.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonD);
        jRadioButtonD.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jRadioButtonD.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDActionPerformed(evt);
            }
        });

        jLabelSkorRealtime.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabelSkorRealtime.setForeground(new java.awt.Color(102, 102, 102));
        jLabelSkorRealtime.setText("Benar:");

        jButtonSelesaiPaksadanKumpul.setBackground(new java.awt.Color(255, 102, 102));
        jButtonSelesaiPaksadanKumpul.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonSelesaiPaksadanKumpul.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSelesaiPaksadanKumpul.setText("Selesai Paksa dan kumpul");
        jButtonSelesaiPaksadanKumpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelesaiPaksadanKumpulActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabelUntukQuizNamaQuiz.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabelUntukQuizNamaQuiz.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUntukQuizNamaQuiz.setText("Quiz");

        jLabelWaktuTersisa.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabelWaktuTersisa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWaktuTersisa.setText("Waktu Tersisa:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelUntukQuizNamaQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWaktuTersisa)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelUntukQuizNamaQuiz)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWaktuTersisa)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonD)
                    .addComponent(jRadioButtonC)
                    .addComponent(jRadioButtonB)
                    .addComponent(jRadioButtonA)
                    .addComponent(jLabelRuangSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 71, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSelesaiPaksadanKumpul)
                .addGap(29, 29, 29))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressBarQuiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelSkorRealtime))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPenandaSoalKeBerapaDariKeBerapa, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPenandaSoalKeBerapaDariKeBerapa)
                .addGap(22, 22, 22)
                .addComponent(jLabelRuangSoal)
                .addGap(30, 30, 30)
                .addComponent(jRadioButtonA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabelSkorRealtime)
                .addGap(26, 26, 26)
                .addComponent(jButtonSelesaiPaksadanKumpul)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAActionPerformed

    private void jButtonSelesaiPaksadanKumpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelesaiPaksadanKumpulActionPerformed
    //checkJawaban();  // Cek terakhir
    selesaiQuiz();
    }//GEN-LAST:event_jButtonSelesaiPaksadanKumpulActionPerformed

    private void jRadioButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBActionPerformed

    private void jRadioButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCActionPerformed

    private void jRadioButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDActionPerformed

    private String getNamaQuiz() {
        try (Connection con = Koneksi.getConnection()) {
            String query = "SELECT nama_quiz FROM tbl_quiz WHERE id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, quizId);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getString("nama_quiz");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
        return "Unknown";
    }

private void loadSoal() {
    try (Connection con = Koneksi.getConnection()) {
        String query = "SELECT * FROM tbl_soal WHERE quiz_id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, quizId);
        ResultSet rs = pst.executeQuery();

        soalList.clear();  // Tambah ini kalau perlu reset
        while (rs.next()) {
            Question q = new Question(
            rs.getInt("id"),
                        rs.getString("pertanyaan"),
                        rs.getString("opsi_a"),
                        rs.getString("opsi_b"),
                        rs.getString("opsi_c"),
                        rs.getString("opsi_d"),
                        rs.getString("jawaban_benar").charAt(0)
                );  // Kode asli
            soalList.add(q);
            System.out.println("Loaded soal: " + q.getPertanyaan());  // Debug
        }
        System.out.println("Total soal loaded: " + soalList.size());
        if (soalList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada soal untuk quiz ini!");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error loading soal: " + ex.getMessage());
    }
}

private void tampilSoal() {
    if (currentSoal >= soalList.size()) {
        selesaiQuiz();
        return;
    }
    Question q = soalList.get(currentSoal);
    jLabelPenandaSoalKeBerapaDariKeBerapa.setText("Soal " + (currentSoal + 1) + " dari " + soalList.size());
    jLabelRuangSoal.setText(q.getPertanyaan());
    jRadioButtonA.setText("A. " + q.getOpsiA());
    jRadioButtonB.setText("B. " + q.getOpsiB());
    jRadioButtonC.setText("C. " + q.getOpsiC());
    jRadioButtonD.setText("D. " + q.getOpsiD());
    group.clearSelection();

    // Tambah refresh UI
    jLabelRuangSoal.revalidate();
    jLabelRuangSoal.repaint();
    System.out.println("Menampilkan soal: " + q.getPertanyaan());  // Debug
}

    private void addJawabListener() {
        ActionListener jawabListener = (ActionEvent e) -> {
            checkJawaban();
            currentSoal++;
            tampilSoal();
        };
        jRadioButtonA.addActionListener(jawabListener);
        jRadioButtonB.addActionListener(jawabListener);
        jRadioButtonC.addActionListener(jawabListener);
        jRadioButtonD.addActionListener(jawabListener);
    }

    private void checkJawaban() {
    char selected = ' ';
    if (jRadioButtonA.isSelected()) selected = 'A';
    else if (jRadioButtonB.isSelected()) selected = 'B';
    else if (jRadioButtonC.isSelected()) selected = 'C';
    else if (jRadioButtonD.isSelected()) selected = 'D';

    if (selected != ' ' && selected == soalList.get(currentSoal).getJawabanBenar()) {
        jumlahBenar++;  // Hanya tambah counter
    }
    // Update label realtime (opsional: tampilkan jumlah benar sementara)
    jLabelSkorRealtime.setText("Benar: " + jumlahBenar + " / " + soalList.size());
    }

    private void startTimer() {
        jProgressBarQuiz.setMaximum(sisaDetik);
        jProgressBarQuiz.setValue(sisaDetik);
        timer = new Timer(1000, (ActionEvent e) -> {
            sisaDetik--;
            jLabelWaktuTersisa.setText("Waktu Tersisa: " + formatWaktu(sisaDetik));
            jProgressBarQuiz.setValue(sisaDetik);
            if (sisaDetik <= 0) {
                timer.stop();
                selesaiQuiz();
            }
        });
        timer.start();
    }

    private void selesaiQuiz() {
    timer.stop();

    // Hitung skor akhir proporsional & bulatkan ke bawah (paling adil)
    double persentase = (double) jumlahBenar / soalList.size();
    skor = (int) Math.floor(persentase * 100);  // Atau Math.round() kalau mau bulat terdekat

    JOptionPane.showMessageDialog(this, 
        "Quiz Selesai!\n" +
        "Jawaban Benar: " + jumlahBenar + " dari " + soalList.size() + "\n" +
        "Skor Akhir: " + skor + " / 100", 
        "Hasil Quiz", JOptionPane.INFORMATION_MESSAGE);

    simpanHasil();  // Simpan skor ke DB
    this.dispose();
    }

    private void simpanHasil() {
    try (Connection con = Koneksi.getConnection()) {
        String query = "INSERT INTO tbl_hasil (mahasiswa_id, quiz_id, skor) VALUES (?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, mahaId);
        pst.setInt(2, quizId);
        pst.setInt(3, skor);  // Skor akhir yang sudah proporsional
        pst.executeUpdate();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error simpan skor: " + ex.getMessage());
    }
    }

    private String formatWaktu(int detik) {
        int menit = detik / 60;
        int s = detik % 60;
        return String.format("%02d:%02d", menit, s);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        new HalamanQuiz(1, 1, 5).setVisible(true);  // Dummy: mahaId=1, quizId=1, waktu=5 menit
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSelesaiPaksadanKumpul;
    private javax.swing.JLabel jLabelPenandaSoalKeBerapaDariKeBerapa;
    private javax.swing.JLabel jLabelRuangSoal;
    private javax.swing.JLabel jLabelSkorRealtime;
    private javax.swing.JLabel jLabelUntukQuizNamaQuiz;
    private javax.swing.JLabel jLabelWaktuTersisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBarQuiz;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonB;
    private javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JRadioButton jRadioButtonD;
    // End of variables declaration//GEN-END:variables
}
